spring.application.name=ProyectoBase2025
specs.dir=/specs/

################### Spring Boot Data Source Configuration ############
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bdfe_bruno?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.initialize=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.batch.job.enabled=false

spring.main.allow-circular-references=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

################### SMTP Mail Configuration ##########################
# Configura estos valores con el servidor SMTP real antes de usar la recuperacion de contraseña.
app.mail.username= # Cambia esto por correo real
app.mail.password= # Cambia esto por token de aplicación
app.mail.smtp.starttls.enable=true
app.mail.smtp.auth=true
app.mail.smtp.host=smtp.gmail.com
app.mail.smtp.port=587
